Repository codesquad-members-2023/be-java-ladder, pull requests merged in 2023-03, with the labels that each got.

#4 [Hyun] step-2 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/RandomGenerator.java
  src/main/java/kr/codesquad/UI.java
  src/test/java/kr/codesquad/LadderTest.java
  src/test/java/kr/codesquad/UITest.java
Labels: step-1, step-2

#7 [감자] step-1 구현
  .gitignore
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  gitignore
  gradlew
  gradlew.bat
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/Command.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Message.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-1

#8 [core] step-1 구현
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutView.java
Labels: step-1

#10 [로이] step-1 구현
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  README.md
  gradlew
  gradlew.bat
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/LadderController.java
  src/main/java/kr/codesquad/model/Generator.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-1

#11 [nino] step-2 구현
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
Labels: step-1, step-2

#14 [poro] step-1 : 기능 구현 완료
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/LadderGameService.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/RandomGenerator.java
  src/main/java/kr/codesquad/Renderer.java
  src/main/java/kr/codesquad/View.java
  src/test/java/StringApiTest.java
  src/test/java/StringBuilderApiTest.java
Labels: step-1

#16 [GOMUNGNAM] step-1 주간 학습 계획 작성
  .gitignore
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  src/main/java/kr/codesquad/Main.java
Labels: step-1

#17 [new-pow] step-2 : 리팩터링
  README.md
  src/main/java/kr/codesquad/ladder/Ladder.java
  src/main/java/kr/codesquad/ladder/LadderMaker.java
  src/main/java/kr/codesquad/util/RandomBoolean.java
  src/main/java/kr/codesquad/util/RandomUtil.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/ladder/LadderTest.java
  src/test/java/kr/codesquad/ladder/util/RandomBoolean.java
Labels: step-2

#22 [Hyun] step-3 구현
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/UI.java
  src/test/java/kr/codesquad/LadderTest.java
  src/test/java/kr/codesquad/UITest.java
Labels: step-3

#32 change. 리뷰상태가 changes_requested 상태이면 자동머지 하지 않음
  .github/workflows/automatic-merge.yml
Labels: enhancement

#42 [ManJu] step-1 구현
  .idea/workspace.xml
  README.md
  src/main/java/LadderGame/Ladder.java
  src/main/java/LadderGame/Main.java
Labels: step-1

#43 [poro] step - 2 : 커밋 로그 수정
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/RandomGenerator.java
  src/main/java/kr/codesquad/Renderer.java
  src/main/java/kr/codesquad/View.java
Labels: step-2

#38 [GOMUNGNAM] step-1 구현
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-1

#41 [Luke] Step-2 구현 (feat. 커밋 쪼개기)
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutputView.java
  src/main/java/kr/codesquad/RandomsGenerator.java
Labels: step-2

#44 [ManJu] step-2 구현
  .idea/workspace.xml
  src/main/java/LadderGame/Ladder.java
  src/main/java/LadderGame/Main.java
Labels: step-2

#45 [로이] step-2 구현
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/ApplicationController.java
  src/main/java/kr/codesquad/model/Generator.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-2

#46 [new-pow] step-3 : 기능 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/LadderGame.java
  src/main/java/kr/codesquad/domain/LadderMaker.java
  src/main/java/kr/codesquad/domain/LadderStep.java
  src/main/java/kr/codesquad/domain/User.java
  src/main/java/kr/codesquad/domain/Users.java
  src/main/java/kr/codesquad/ladder/Ladder.java
  src/main/java/kr/codesquad/ladder/LadderMaker.java
  src/main/java/kr/codesquad/util/RandomBoolean.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderTest.java
Labels: step-3

#47 [Dewey] step-1 구현
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  gradle/wrapper/gradle-wrapper.jar
  src/InputView.java
  src/LadderGame.java
  src/LadderMap.java
  src/OutputView.java
Labels: step-1

#53 [GOMUNGNAM] step-2 구현 및 3월 8일 수요일 학습 계획 작성
  README.md
  src/main/java/kr/codesquad/LadderMaker.java
Labels: step-2

#55 [core] step-2 구현
  .idea/.name
  .idea/aws.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  out/production/classes/kr/codesquad/InputView.class
  out/production/classes/kr/codesquad/LadderGame.class
  out/production/classes/kr/codesquad/Main.class
  out/production/classes/kr/codesquad/OutView.class
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/OutView.java
  src/main/java/kr/codesquad/Point.java
Labels: step-2

#50 [ManJu] step-3 구현
  .idea/workspace.xml
  src/main/java/LadderGame/Ladder.java
  src/main/java/LadderGame/Main.java
Labels: step-3

#51 [Dewey] step-2 구현
  src/Application.java
  src/InputView.java
  src/LadderGame.java
  src/LadderMap.java
  src/OutputView.java
Labels: step-2

#54 [poro] step - 3 : 사다리 모양 개선 구현
  README.md
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/LadderGameService.java
  src/main/java/kr/codesquad/RandomGenerator.java
  src/main/java/kr/codesquad/Renderer.java
  src/main/java/kr/codesquad/View.java
  src/test/java/JcfTest.java
  src/test/java/Point.java
Labels: step-3

#61 [Birdie] Step - 2 리팩토링 맛보기
  src/main/java/kr/codesquad/AppConfig.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Controller.java
  src/main/java/kr/codesquad/domain/laddergenerator/Ladder.java
  src/main/java/kr/codesquad/domain/laddergenerator/LadderGenerator.java
  src/main/java/kr/codesquad/domain/laddergenerator/StepOneLadder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/LadderView.java
Labels: step-2

#62 [Cire] Step-2 구현 : 리펙토링 및 버그 수정
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/.idea/misc.xml
  src/.idea/uiDesigner.xml
  src/.idea/workspace.xml
  src/main/java/kr/codesquad/InputAdaptor.java
  src/main/java/kr/codesquad/InputConverter.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Point.java
  src/main/java/kr/codesquad/PointType.java
  src/main/java/kr/codesquad/Status.java
  src/main/java/kr/codesquad/Type.java
  src/main/java/kr/codesquad/View.java
Labels: step-2

#64 [ManJu] step-4 구현중
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/main/java/LadderGame/Main.java
  src/main/java/LadderGame/domain/Ladder.java
  src/main/java/LadderGame/domain/Line.java
  src/main/java/LadderGame/view/Input.java
  src/main/java/LadderGame/view/Output.java
Labels: step-4

#67 [new-pow] step-4 : Line 기능 테스트
  src/main/java/kr/codesquad/ladder/domain/Ladder.java
  src/main/java/kr/codesquad/ladder/domain/LadderGame.java
  src/main/java/kr/codesquad/ladder/domain/Line.java
  src/main/java/kr/codesquad/ladder/view/InputView.java
  src/main/java/kr/codesquad/ladder/view/OutputView.java
  src/test/java/kr/codesquad/domain/LadderTest.java
  src/test/java/kr/codesquad/ladder/domain/LineTest.java
Labels: step-4

#63 [로이] Step-3 구현
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/controller/ApplicationController.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
  src/main/java/kr/codesquad/view/View.java
Labels: step-3

#69 [Dewey] step-3 구현
  src/InputView.java
  src/LadderGame.java
  src/LadderMap.java
  src/Line.java
  src/OutputView.java
  src/Player.java
Labels: step-3

#71 [Birdie] Step - 3 사다리 모양 개선
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Controller.java
  src/main/java/kr/codesquad/domain/laddergenerator/Ladder.java
  src/main/java/kr/codesquad/domain/laddergenerator/LadderMaker.java
  src/main/java/kr/codesquad/view/LadderView.java
Labels: step-3

#72 [ManJu] step-4 구현: 리팩토링 & 테스트 추가 + Revert문제 해결
  .gitignore
  .idea/git_toolbox_prj.xml
  .idea/uiDesigner.xml
  .idea/workspace.xml
  src/main/java/LadderGame/Ladder.java
  src/main/java/LadderGame/Main.java
  src/main/java/LadderGame/domain/Ladder.java
  src/main/java/LadderGame/domain/Line.java
  src/main/java/LadderGame/view/Input.java
  src/main/java/LadderGame/view/Output.java
  src/test/java/LadderTest.java
  src/test/java/LineTest.java
Labels: step-4

#73 [GOMUNGNAM] step-3 구현 및 주간 학습 계획 수정, 목요일 일일 학습 계획 작성
  .idea/uiDesigner.xml
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/model/Converter.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/model/LadderMaker.java
  src/main/java/kr/codesquad/view/InputView.java
  src/main/java/kr/codesquad/view/OutputView.java
Labels: step-3

#74 [Luke] Step-3에 대한 리팩토링
  README.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/RandomsGenerator.java
  src/main/java/kr/codesquad/domain/Header.java
  src/main/java/kr/codesquad/domain/LadderMaker.java
  src/main/java/kr/codesquad/domain/RandomsGenerator.java
  src/main/java/kr/codesquad/view/Viewer.java
Labels: step-3

#75 [poro] step - 4 : 테스트 코드 작성
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGameController.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/RandomGenerator.java
  src/main/java/kr/codesquad/Renderer.java
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/utils/RandomGenerator.java
  src/main/java/kr/codesquad/utils/RandomUtils.java
  src/main/java/kr/codesquad/view/Renderer.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/ExceptionTest.java
  src/test/java/LadderTest.java
  src/test/java/LineTest.java
  src/test/java/RendererTest.java
Labels: step-4

#76 [Cire] Step-3
  src/main/java/kr/codesquad/InputConverter.java
  src/main/java/kr/codesquad/InputTerminal.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/Point.java
  src/main/java/kr/codesquad/PointType.java
  src/main/java/kr/codesquad/View.java
Labels: step-3

#77 [Hyun] step-5 구현 - 애플리케이션 완성
  LearningPlan.md
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Game.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/People.java
  src/main/java/kr/codesquad/domain/Person.java
  src/main/java/kr/codesquad/domain/RandomGenerator.java
  src/main/java/kr/codesquad/dto/PersonResultPair.java
  src/main/java/kr/codesquad/view/Client.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/kr/codesquad/domain/GameTest.java
  src/test/java/kr/codesquad/domain/LadderTest.java
  src/test/java/kr/codesquad/domain/LineTest.java
  src/test/java/kr/codesquad/domain/PeopleTest.java
  src/test/java/kr/codesquad/domain/PersonTest.java
Labels: step-5

#78 [로이] step-4 구현
  README.md
  src/main/java/kr/codesquad/controller/ApplicationController.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/test/java/kr/codesquad/model/LadderTest.java
Labels: step-4

#79 [core] step-3 구현
  README.md
  src/main/java/kr/codesquad/InputView.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderGame.java
  src/main/java/kr/codesquad/LadderMaker.java
  src/main/java/kr/codesquad/Line.java
  src/main/java/kr/codesquad/OutView.java
  src/main/java/kr/codesquad/Participants.java
  src/main/java/kr/codesquad/Point.java
  src/main/java/kr/codesquad/Shape.java
  src/main/java/kr/codesquad/View.java
Labels: step-3

#81 [Hyun] step-5 가독성 향상
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Person.java
  src/test/java/kr/codesquad/domain/GameTest.java
  src/test/java/kr/codesquad/domain/LadderTest.java
  src/test/java/kr/codesquad/domain/LineTest.java
  src/test/java/kr/codesquad/domain/PeopleTest.java
Labels: step-5

#82 [감자] Step-3 요구사항에 따라 사다리 모양을 개선합니다.
  README.md
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/CharLadder.java
  src/main/java/kr/codesquad/Command.java
  src/main/java/kr/codesquad/Ladder.java
  src/main/java/kr/codesquad/LadderHeader.java
  src/main/java/kr/codesquad/ListLadder.java
  src/main/java/kr/codesquad/Message.java
  src/main/java/kr/codesquad/OutputView.java
Labels: step-3

#83 [Birdie] Step - 4
  src/main/java/kr/codesquad/Main.java
  src/main/java/kr/codesquad/domain/Controller.java
  src/main/java/kr/codesquad/domain/laddergenerator/Ladder.java
  src/main/java/kr/codesquad/domain/laddergenerator/LadderMaker.java
  src/main/java/kr/codesquad/domain/laddergenerator/Line.java
  src/main/java/kr/codesquad/view/LadderView.java
Labels: step-4

#84 [poro] step - 5 결과 출력 기능 구현
  src/main/java/kr/codesquad/controller/LadderGameController.java
  src/main/java/kr/codesquad/domain/Ladder.java
  src/main/java/kr/codesquad/domain/Line.java
  src/main/java/kr/codesquad/domain/Player.java
  src/main/java/kr/codesquad/domain/PlayerRepository.java
  src/main/java/kr/codesquad/domain/Result.java
  src/main/java/kr/codesquad/view/Renderer.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/LadderTest.java
  src/test/java/RendererTest.java
Labels: step-5

#85 [로이] step-5 구현
  README.md
  src/main/java/kr/codesquad/controller/ApplicationController.java
  src/main/java/kr/codesquad/model/Ladder.java
  src/main/java/kr/codesquad/view/View.java
  src/test/java/kr/codesquad/model/LadderTest.java
Labels: step-5

#86 [감자] strep-4 테스트 코드 작성합니다
  src/main/java/kr/codesquad/Application.java
  src/main/java/kr/codesquad/ladder/domain/CharLadder.java
  src/main/java/kr/codesquad/ladder/domain/LadderHeader.java
  src/main/java/kr/codesquad/ladder/domain/ListLadder.java
  src/main/java/kr/codesquad/ladder/exception/CommandException.java
  src/main/java/kr/codesquad/ladder/view/Command.java
  src/main/java/kr/codesquad/ladder/view/Message.java
  src/main/java/kr/codesquad/ladder/view/OutputView.java
  src/test/java/kr/codesquad/ladder/domain/CharLadderTest.java
  src/test/java/kr/codesquad/ladder/domain/LadderHeaderTest.java
  src/test/java/kr/codesquad/ladder/domain/ListLadderTest.java
  src/test/java/kr/codesquad/ladder/view/CommandTest.java
Labels: step-4

#87 [ManJu] step-5 구현: 기능 구현 & 테스트 구현 X
  .gitignore
  .idea/workspace.xml
  src/main/java/LadderGame/Main.java
  src/main/java/LadderGame/domain/Ladder.java
  src/main/java/LadderGame/domain/LadderGameResult.java
  src/main/java/LadderGame/domain/LadderInOutData.java
  src/main/java/LadderGame/domain/Line.java
  src/main/java/LadderGame/view/Input.java
  src/main/java/LadderGame/view/Output.java
  src/test/java/LadderTest.java
Labels: step-5
